workflows and tests updated
MobilityDB/JMEOS pull request #7
Opened 2024-08-30 15:32 UTC by 1-ARIjitS

2024-09-06 21:57 UTC, mschoema requested changes

2024-09-06 21:57 UTC, mschoema commented on .github/workflows/deploy_javadoc.yml
> +      - pr-fix
This workflow should only run on the main branch, since it deploys to gh-pages

2024-09-06 21:57 UTC, mschoema commented on .github/workflows/maven.yml
> +      - pr-fix
Here I would simply let the workflow run on all branches except for gh-pages:

```
push:
    branch_ignore: gh-pages
pull_request:
    branch_ignore: gh-pages
```

2024-09-07 08:38 UTC, 1-ARIjitS commented on .github/workflows/deploy_javadoc.yml
> +      - pr-fix
updated with only main branch

2024-09-07 08:38 UTC, 1-ARIjitS commented on .github/workflows/maven.yml
> +      - pr-fix
updated with ignoring the gh-pages branch ready to merge

2024-09-07 23:23 UTC, mschoema approved these changes

2024-09-07 23:24 UTC, merged